server:
  port: 8081 # ?? ??

spring:
  config:
    import: classpath:config/conf-log.yml
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://minkyu1128.synology.me:43306/ens?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    username: ens_user
    password: xit5811807
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: update

  main:
    allow-bean-definition-overriding: true # userDetailService ?? ??? ?? ?? ??? ??? ??? ??? ?? ??


custom:
  oauth:
    url: http://localhost:${server.port}
